---
env:
  CIRRUS_CLONE_DEPTH: 1

task:
  only_if: $CIRRUS_PR != ''
  persistent_worker: {}
  env:
    PATH: /usr/local/bin:${PATH}
  clone_script: |
    if [ ! -z "$CIRRUS_PR" ]; then
      git clone --depth 1 https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
      if [ ! -f "${CIRRUS_WORKING_DIR}"/"${CIRRUS_PR_TITLE%%:*}"/Makefile ]; then
        echo "Add proper PR TITLE like <CATEGORY>/<PORTNAME>: YOUR CHANGES"
        exit 1
      fi
    else
      echo "Only for PR"
      exit 1
    fi
  debug_script:
    - echo $CIRRUS_BRANCH
  test_script:
    - poudriere ports -c -m null -M ${CIRRUS_WORKING_DIR} -p ${CIRRUS_PR}
    - poudriere testport -j 143 -p ${CIRRUS_PR} -b latest ${CIRRUS_PR_TITLE%%:*}
  always:
    cleanup_script:
      - poudriere pkgclean -j 143 -p ${CIRRUS_PR} -A -y
      - yes | poudriere ports -d -k -p ${CIRRUS_PR}
